version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Azuzag86
      POSTGRES_DB: foodgram
    env_file:
    - ./.env

  backend:
    image: sobolyara/infra_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
    - ./.env


  frontend:
    image: sobolyara/infra_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
      
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/redoc/
      - static_value:/etc/nginx/html/static/
      - media_value:/etc/nginx/html/media/
    depends_on:
      - backend
      - frontend
    env_file:
      - ./.env

volumes:
  postgres_data:
  static_value:
  media_value:
